//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class www_africatwin_czEntities : DbContext
    {
        public www_africatwin_czEntities()
            : base("name=www_africatwin_czEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<at_akce> at_akce { get; set; }
        public virtual DbSet<at_atav_ucast> at_atav_ucast { get; set; }
        public virtual DbSet<at_counter> at_counter { get; set; }
        public virtual DbSet<at_dokumenty> at_dokumenty { get; set; }
        public virtual DbSet<at_emaily> at_emaily { get; set; }
        public virtual DbSet<at_hledat> at_hledat { get; set; }
        public virtual DbSet<at_hodnoceni> at_hodnoceni { get; set; }
        public virtual DbSet<at_kameniste> at_kameniste { get; set; }
        public virtual DbSet<at_odkazy> at_odkazy { get; set; }
        public virtual DbSet<at_pokec> at_pokec { get; set; }
        public virtual DbSet<at_polozky> at_polozky { get; set; }
        public virtual DbSet<at_polozky_test> at_polozky_test { get; set; }
        public virtual DbSet<at_users> at_users { get; set; }
    }
}
