//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_atav_ucast
    {
        public int akce { get; set; }
        public int user_id { get; set; }
        public Nullable<int> pocet_osob { get; set; }
        public string d_1 { get; set; }
        public string d_2 { get; set; }
        public string d_3 { get; set; }
        public string d_4 { get; set; }
        public string d_5 { get; set; }
        public string d_6 { get; set; }
        public string d_7 { get; set; }
        public string d_8 { get; set; }
        public string d_9 { get; set; }
        public string d_10 { get; set; }
        public string jezdeni { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string ubytovani { get; set; }
        public Nullable<int> pocet_deti { get; set; }
        public string ucast_dny { get; set; }
        public string penze_dny { get; set; }
    }
}
