//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_akce
    {
        public int id_akce { get; set; }
        public string nazev { get; set; }
        public string povidani { get; set; }
        public Nullable<int> id_kamene { get; set; }
        public Nullable<System.DateTime> termin_od { get; set; }
        public Nullable<System.DateTime> termin_do { get; set; }
        public System.DateTime insert_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public string upoutavka { get; set; }
        public string uzavreno { get; set; }
        public string formular { get; set; }
        public string formular_dny { get; set; }
        public string formular_bydleni { get; set; }
        public string formular_jezdeni { get; set; }
        public string data_1 { get; set; }
        public string data_2 { get; set; }
        public string data_3 { get; set; }
        public string data_4 { get; set; }
        public string data_5 { get; set; }
        public Nullable<int> data_6 { get; set; }
        public Nullable<System.DateTime> data_7 { get; set; }
        public string formular_penze { get; set; }
        public string formular_deti { get; set; }
    }
}
