//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_counter
    {
        public int count_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public System.DateTime datum { get; set; }
        public string info { get; set; }
        public string timer_info { get; set; }
    }
}
