//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_dokumenty
    {
        public int id_dokumentu { get; set; }
        public int id_skupiny { get; set; }
        public System.DateTime dat_vlozeni { get; set; }
        public string nazev { get; set; }
        public string popis { get; set; }
        public string nazev_puvodni { get; set; }
        public string nazev_systemovy { get; set; }
        public Nullable<int> user_id { get; set; }
        public string typ { get; set; }
    }
}
