//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_hodnoceni
    {
        public int polozka_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> polozka_pod_id { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public Nullable<int> hodnoceni { get; set; }
    }
}
