//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_kameniste
    {
        public int id_kamene { get; set; }
        public Nullable<int> id_krabice { get; set; }
        public Nullable<int> user_id { get; set; }
        public string puvodni_nazev { get; set; }
        public string systemovy_nazev { get; set; }
        public string nazev_kamene { get; set; }
        public Nullable<int> sizeX { get; set; }
        public Nullable<int> sizeY { get; set; }
        public string popis_kamene { get; set; }
        public Nullable<System.DateTime> datum_vlozeni { get; set; }
        public string typ_kamene { get; set; }
        public string vyska { get; set; }
        public string sirka { get; set; }
    }
}
