//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_odkazy
    {
        public int odkaz_id { get; set; }
        public string adresa { get; set; }
        public string popis { get; set; }
        public string typ { get; set; }
        public System.DateTime datum { get; set; }
        public string username { get; set; }
        public string user_id { get; set; }
        public int active { get; set; }
        public string logo { get; set; }
    }
}
