//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_pokec
    {
        public int pokec_id { get; set; }
        public Nullable<int> parent_pokec_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> adresat_id { get; set; }
        public string adresat_name { get; set; }
        public string pokec { get; set; }
        public string jmeno { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> del { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
