//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_polozky
    {
        public int polozka_id { get; set; }
        public string kategorie { get; set; }
        public string podkategorie { get; set; }
        public Nullable<int> sablona { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public Nullable<int> active { get; set; }
        public string nadpis { get; set; }
        public string text { get; set; }
        public System.DateTime insert_date { get; set; }
        public System.DateTime public_date { get; set; }
        public System.DateTime expire_date { get; set; }
        public string cena { get; set; }
        public string mena { get; set; }
        public string title { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> polozka_nad_id { get; set; }
        public Nullable<int> poradi { get; set; }
    }
}
