//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfricaTwin.cz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_users
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string overeni_emailu { get; set; }
        public Nullable<System.DateTime> datum_overeni_emailu { get; set; }
        public string motocykl { get; set; }
        public int active { get; set; }
        public Nullable<int> profil { get; set; }
        public string vyroben { get; set; }
        public string jmeno { get; set; }
        public string prijmeni { get; set; }
        public string okres { get; set; }
        public string narozen { get; set; }
        public string telefon { get; set; }
        public string icq { get; set; }
        public string skype { get; set; }
        public string text_moto { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string foto_moto { get; set; }
        public string foto_user { get; set; }
        public int foto { get; set; }
        public string odber_diskuse { get; set; }
        public string www { get; set; }
        public string msn { get; set; }
        public string spz { get; set; }
        public string mesto { get; set; }
        public Nullable<decimal> psc { get; set; }
        public string ulice { get; set; }
        public string cp { get; set; }
        public Nullable<System.DateTime> aktualizace { get; set; }
        public string prava { get; set; }
        public string user_profil_foto { get; set; }
        public string gps_lat { get; set; }
        public string gps_lng { get; set; }
    }
}
